streaming_hostname: 'stream-fxpractice.oanda.com'
host: 'api-fxtrade.oanda.com'
port: 443
ssl: 'true'
token: '36d05c504600ee53cbaebd2d7fd872f6-ec6ea1868a87be65621c6c23ba0e9fe1'
username: 'pszoniu'
account: '101-004-12033863-001'

